version: '3.6'
services:
    php-docker-isolation-provider:
        image: deepf/php-docker-isolation-provider:main
        networks:
            - deep
        ports:
            - 3021:3021
        restart: always
        environment: {}
networks:
    deep:
        driver: bridge
